version: '3.7'

services:
  
  threetenant.web.public:
    image: ${DOCKER_REGISTRY-}threetenantwebpublic
    container_name: threetenantwebpublic_container
    build:
      context: ../../
      dockerfile: src/ThreeTenant.Web.Public/Dockerfile
    environment:
      - ConnectionStrings__Default=Server=mssqlDb;Database=ThreeTenantDb;User=sa;Password=Super_Encrypted_Passw0rd!
    ports:
      - "44303:443"
    networks:
      - threetenant

networks:
  threetenant:
    external:
      name: threetenant