version: '3.7'

services:      

  threetenant.web.host:
    image: ${DOCKER_REGISTRY-}threetenantwebhost
    container_name: threetenantwebhost_container
    build:
      context: ../../
      dockerfile: src/ThreeTenant.Web.Host/Dockerfile
    environment:
      - ConnectionStrings__Default=Server=mssqlDb;Database=ThreeTenantDb;User=sa;Password=Super_Encrypted_Passw0rd!
      - Abp__RedisCache__ConnectionString=localhost:6379
    ports:
      - "44301:443"
    networks:
      - threetenant

networks:
  threetenant:
    external:
      name: threetenant