version: '3.7'

services:

  mssqlDb:
    container_name: mssqlDb_container
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: Super_Encrypted_Passw0rd!
      ACCEPT_EULA: Y
    volumes:
      - mssqlDb-data:/var/opt/mssql
    networks:
      - threetenant

  redis:
    image: redis:alpine
    container_name: redis_container
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - threetenant

volumes:
  mssqlDb-data:
   name: "mssqlDb-data"

networks:
  threetenant:
    external:
      name: threetenant