version: '3.7'

services:

  threetenant.migrator:
    image: ${DOCKER_REGISTRY-}threetenantmigrator
    container_name: threetenantmigrator_container
    build:
      context: ../../
      dockerfile: src/ThreeTenant.Migrator/Dockerfile
    environment:
      - ASPNETCORE_Docker_Enabled=true
      - ConnectionStrings__Default=Server=mssqlDb;Database=ThreeTenantDb;User=sa;Password=Super_Encrypted_Passw0rd!
    networks:
      - threetenant
      
networks:
  threetenant:
    external:
      name: threetenant